### ISSUE TITLE
Unresolved reference 'matcherpcre'

### ISSUE THREAD

**Issue by itamaker** [tenta-browser/go-video-downloader#1]
- dep ensure -add github.com/tenta-browser/go-video-downloader
- matcherpcre.NewEngine()
- Unresolved reference 'matcherpcre'

**Comment by windom** [comment]
Hi!

Added a little more details to the README in d45939c0797db539ea40c51830d6e515544c7ed9.

To make it work with dep you could do: `dep ensure -add github.com/tenta-browser/go-pcre-matcher/matcherpcre`
